name: Run Discord Bot

on:
  push:
    branches:
      - main  # Executa o workflow quando houver push na branch "main"

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: üöÄ Checkout do c√≥digo
        uses: actions/checkout@v4

      - name: üõ†Ô∏è Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: üì¶ Instalar depend√™ncias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: üîë Configurar vari√°veis de ambiente
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          GOOGLE_CLIENT_EMAIL: ${{ secrets.GOOGLE_CLIENT_EMAIL }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_PRIVATE_KEY: ${{ secrets.GOOGLE_PRIVATE_KEY }}
          GOOGLE_PRIVATE_KEY_ID: ${{ secrets.GOOGLE_PRIVATE_KEY_ID }}
          GOOGLE_PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          MENTION_CHANNEL_ID: ${{ secrets.MENTION_CHANNEL_ID }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
        run: python bot.py  # Ajuste o nome do seu script se necess√°rio
